<a href="https://colab.research.google.com/github/aathi1208/numpy-/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
lst=[1,2,3,4,6]
print("Enter a number to append")
a=int(input())
lst.append(a)
print(lst)

Enter a number to append
5
[1, 2, 3, 4, 6, 5]


In [ ]:
lst=[1,2,3,4,6]
print("Enter a number to remove")
a=int(input())
lst.remove(a)
print(lst)

Enter a number to remove
2
[1, 3, 4, 6]


In [ ]:
lst=[1,2,3,4,6]
print("Enter a index to pop")
a=int(input())
lst.pop(a)
print(lst)

Enter a index to pop
2
[1, 2, 4, 6]


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
soi=np.arange(5,12,2)
print(soi)

[ 5  7  9 11]


In [ ]:
a = np.array([1.,2.,3.],dtype=np.int64)
b = np.array([[2,3,4],[3,4,5]])
print(a.dtype)
print(a)

int64
[1 2 3]


In [ ]:
g=np.linspace(0, 10, num=11)
print(g)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
q=np.random.random((2,3))
print(q)

[[0.78279252 0.19406155 0.26076088]
 [0.83157899 0.24901201 0.81322663]]


In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a[:2,1:3]
print(a)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
r1=a[1, : ]
r2=a[1:2, : ]
r3=a[[1], : ]
print(r1,r1.shape)
print(r2,r2.shape)
print(r3,r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [ ]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
bool_idx=(a>2)
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [ ]:
a=np.array([1,2,3,4,5,6,7,8])
print(np.argmax(a))
print(np.argmin(a))
print(np.argsort(a))
print(np.where(a>5)[0])
print(np.where(a>=a[np.argmax(a)])[0])

7
0
[0 1 2 3 4 5 6 7]
[5 6 7]
[7]
